### ISSUE TITLE
Challenge 1 Feedback

### ISSUE THREAD

**Issue by aespaldi** [jamiejamiebobamie/CS-2.2-Advanced-Recursion-and-Graphs#1]
Challenge 1 Feedback : 4/20

Overall: This is a good start but not finished.  Make sure code runs on provided sample input, test file runs, and code is well documented. 

Feedback based on Challenge 1 Rubric: 
- Works: 0
  - Use a dictionary to represent the adjacency list - no need to implement a LinkedList here. 
  - No output - readGraph method is never called. 

- Documentation: 1
  - Not all methods have doc strings.    
  - Use PEP8 styling : snake_case not camelCase for method names. 
- Code Organization: 2
- Testing: 1
  - Use unittest or other library - test code does not run. 
  - no error handling

**Comment by jamiejamiebobamie** [comment]
I've updated my code and added a message to you in my challenge1.py file, with what has been updated. I tried to use unittests with the python module, but had trouble overriding the test class's init function. I commented out out all of the new tests and reimplemented the old ones and they ran / worked for me. Thank you for your comments btw. With your feedback I'm definitely improving / honing in on my shortcomings. Thanks!

**Comment by aespaldi** [comment]
Challenge 1: 6/20 Not passing
(Regrade on 8/14/2019 )


- Works 0/8
  - Code crashes on this line 69   `edges.append((int(entry[1]), int(entry[3])))` Check your read method
  - Code should accept an input file as an arg from the console - not only read graph_data.txt.

- Documentation  2
  - Still not meeting PEP8 guidelines - run `pycodestyle` to see errors. 
- Code Organization 2
- Testing 2

**Comment by aespaldi** [comment]
Challenge 1: 12/20 pass
(Regrade on 8/17/2019 )


- Works 5/8
- Documentation  3
- Code Organization 2
- Testing 2
